### ISSUE TITLE
invalid flag: --export=malloc

### ISSUE THREAD

**Issue by rinfx** [wasilibs/nottinygc#20]
Hi, when I use v0.4.0, I meet this error
```
github.com/wasilibs/nottinygc@v0.4.0/init.go:9:14: invalid flag: --export=malloc
```

How can I fix it?

**Comment by anuraaga** [comment]
Hi @rinfx - are you using TinyGo 0.28.x? v0.4.0 requires it as the minimum version and I believe using an older version would cause that error message.

**Comment by rinfx** [comment]
Thanks! Switch to TinyGo 0.28.x can fix this problem
