### ISSUE TITLE
can nottinygc support wasm?

### ISSUE THREAD

**Issue by Taoja** [wasilibs/nottinygc#48]
tinygo gc has memory overflow in wasm。
can nottinygc support wasm?

**Comment by anuraaga** [comment]
Hi @Taoja - nottinygc is meant to be used with Wasm. However, depending on usage there are memory leaks that we haven't been able to resolve, it's unfortunately difficult when the compiler (TinyGo) and the GC library are decoupled. I'm hoping the official Go compiler's support for `wasmexport` will be a good way forward.
